services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: myrox-postgres-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
      - ./myROX-api/database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - myrox-network

  # API myROX
  api:
    build:
      context: ./myROX-api
      dockerfile: Dockerfile
    container_name: myrox-api-prod
    environment:
      PORT: ${API_PORT}
      NODE_ENV: ${API_NODE_ENV}
      DATABASE_URL: ${API_DATABASE_URL}
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - myrox-network

  # Application Web Frontend
  web:
    build:
      context: ./myrox-web
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${WEB_NODE_ENV}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
    container_name: myrox-web-prod
    environment:
      NODE_ENV: ${WEB_NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - myrox-network

volumes:
  postgres_data_prod:
    driver: local

networks:
  myrox-network:
    driver: bridge
