services:
  # Application Web Frontend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myrox-web
    restart: always
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://host.docker.internal:3001
    ports:
      - "3002:3000"
    networks:
      - myrox-network

networks:
  myrox-network:
    driver: bridge 