name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/myrox
            git pull
            # Suppression des dossiers inutiles (mobile/tests/IDE)
            rm -rf myROX myROXTests myROXUITests myROX_watch 'myROX_watch AppTests' 'myROX_watch AppUITests' MyROX.xcodeproj .idea
            # Suppression des fichiers inutiles (mobile/Xcode/docs)
            rm -f MyROX-watch-Watch-App-Info.plist 'myROX_watch Watch App.entitlements' README.md DOCKER_SETUP.md PGADMIN_SETUP.md MyROX.xcodeproj .idea
            docker compose build
            docker compose up -d --remove-orphans
