name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déploiement sur le VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          # Supprimez cette ligne :
          # passphrase: ${{ secrets.VPS_SSH_KEY_PASSPHRASE }}
          debug: true
          script: |
            cd /opt/myrox
            git pull
            rm -rf myROX myROXTests myROXUITests myROX_watch 'myROX_watch AppTests' 'myROX_watch AppUITests' MyROX.xcodeproj .idea
            rm -f MyROX-watch-Watch-App-Info.plist 'myROX_watch Watch App.entitlements' README.md DOCKER_SETUP.md PGADMIN_SETUP.md MyROX.xcodeproj 
            docker compose -f docker-compose.prod.yml build
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
